path:  /Users/zemin.yan/Desktop/images/
jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  url: jdbc:mysql://localhost:3306/product_db?CreateDatabaseIfNotExist=true
  username: root
  password: 123456
  open-in-view: true
  show-sql: true
  enable: true
  hibernate:
    ddl-auto: update
servlet:
  enabled: true
  max-file-size: 10485760
